---
title: "Hierarchical Bayesian Model for Responses"
author: "Kristian Brock"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
bibliography: C:/Users/krist/Dropbox/Projects/library.bib
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Hierarchical Bayesian model for responses
@Thall2003 described a method for analysing treatment effects of a common intervention in several sub-types of a single disease.
The treatment effects are assumed to be different but exchangeable and correlated.
Observing good efficacy in one cohort, for example, increases one's expectations of efficacy in other cohorts.

They demonstrate the hierarchical model in a trial with binary response outcomes and in another with time-to-event outcomes.
This vignette describes the sarcoma example with binary response outcomes.
The authors provide WinBUGS code for each example in the appendix of their paper [@Thall2003].
We port their example to Stan and illustrate usage with the example given in the paper.


# Implementation in `trialr`
The model is compiled in `trialr` under the `ThallHierarchicalBinary` slot of the `stanmodels` object.

Statistically, the authors assume that in a trial of $k$ disease subtypes, the treatment effects are drawn from the same common normal distribution

$\rho_1, ..., \rho_k \sim N(\mu, \sigma^2)$

As is the convention in BUGS, the authors define normal distributions by a precision parameter $\tau$ as opposed to the standard deviation parameter $\sigma$ used here.
We have re-specified the model to comply with the Stan convention of using standard deviation.
The authors use a normal hyperprior on $\mu$, and a gamma hyperprior on $\tau$, equivalent to an inverse gamma hyperprior on $\sigma$.

We observe $x_i$ responses in $n_i$ patients in disease sub-type $i$.
The rate of response in subtype $i$ is $p_i = \text{logit}^{-1}(\rho_i)$.
Each $x_i$ is assumed to be binomially distributed with success parameter $p_i$.
In Stan, that relationship is described as
`x ~ binomial_logit(n, rho);`

The treatment is judged to be worthy of further investigation in cohort $i$ if

$\text{Pr}\left\{ p_i > \theta | \mathcal{D} \right\} > q$

where $\theta$ is the minimum required response rate, and $q$ is the required certainty to approve.
In their provided example, @Thall2003 use $\theta = 0.3$ and $q=?$.



# References
